import { useMemo } from 'react'
import { useNotify } from '../components/notifications.jsx'

/** Faculty toasts auto-dismiss after ~3.5s (Admin default is 5s). */
export const FACULTY_TOAST_MS = 3500

export const SCORE_LOCKED_MSG =
  'Deadline has passed. Scores are locked. Contact admin to request a grade correction.'
export const FACULTY_ANNOUNCEMENT_TOAST_MS = 3000

export const FACULTY_TOAST_ID = {
  dashboardFetchError: 'dashboard-fetch-error',
  dashboardActivitiesError: 'dashboard-activities-error',
  semesterRequiredError: 'semester-required-error',
  curriculumFetchError: 'curriculum-fetch-error',
  sectionsFetchError: 'sections-fetch-error',
  subjectsFetchError: 'subjects-fetch-error',
  announcementsFetchError: 'announcements-fetch-error',
  announcementAddSuccess: 'announcement-add-success',
  announcementAddError: 'announcement-add-error',
  announcementUpdateSuccess: 'announcement-update-success',
  announcementUpdateError: 'announcement-update-error',
  announcementDownload: 'announcement-download',
  announcementImageType: 'announcement-image-type',
  announcementImageSize: 'announcement-image-size',
  assignmentAddSuccess: 'assignment-add-success',
  assignmentAddError: 'assignment-add-error',
  assignmentEditSuccess: 'assignment-edit-success',
  assignmentEditError: 'assignment-edit-error',
  assignmentDeleteSuccess: 'assignment-delete-success',
  assignmentDeleteError: 'assignment-delete-error',
  scoreEditSuccess: 'score-edit-success',
  scoreUpdateSuccess: 'score-update-success',
  assignmentFileSizeError: 'assignment-file-size-error',
  assignmentFileTypeError: 'assignment-file-type-error',
  scoreEditError: 'score-edit-error',
  assignmentSubjectError: 'assignment-subject-error',
  assignmentGradeError: 'assignment-grade-error',
  deadlineExpired: 'deadline-expired',
  activityAddSuccess: 'activity-add-success',
  activityAddError: 'activity-add-error',
  activityEditSuccess: 'activity-edit-success',
  activityEditError: 'activity-edit-error',
  activityDeleteSuccess: 'activity-delete-success',
  activityDeleteError: 'activity-delete-error',
  activityScoreSuccess: 'activity-score-success',
  activityScoreError: 'activity-score-error',
  activityFileSizeError: 'activity-file-size-error',
  activityFileTypeError: 'activity-file-type-error',
  activitySubjectError: 'activity-subject-error',
  activityGradeError: 'activity-grade-error',
  activityDeadlineExpired: 'activity-deadline-expired',
  studyMaterialsFetchError: 'study-materials-fetch-error',
  quizFetchError: 'quiz-fetch-error',
  quizAddSuccess: 'quiz-add-success',
  quizAddError: 'quiz-add-error',
  quizEditSuccess: 'quiz-edit-success',
  quizEditError: 'quiz-edit-error',
  quizDeleteSuccess: 'quiz-delete-success',
  quizDeleteError: 'quiz-delete-error',
  quizSemesterError: 'quiz-semester-error',
  quizHideSuccess: 'quiz-hide-success',
  quizUnhideSuccess: 'quiz-unhide-success',
  quizVisibilityError: 'quiz-visibility-error',
  quizPasswordError: 'quiz-password-error',
  quizPasswordVerified: 'quiz-password-verified',
  originalityFetchError: 'originality-fetch-error',
  originalityDeleteSuccess: 'originality-delete-success',
  originalityDeleteError: 'originality-delete-error',
  originalityCreateError: 'originality-create-error',
}

export const FACULTY_MSG = {
  dashboard: {
    loadFailed: 'Failed to load dashboard data.',
  },
  studyMaterial: {
    added: 'Study material added successfully.',
    addFailed: 'Failed to add study material.',
    updated: 'Study material updated successfully.',
    updateFailed: 'Failed to update study material.',
    deleted: 'Study material deleted successfully.',
    deleteFailed: 'Failed to delete study material.',
    loadFailed: 'Failed to load study materials.',
    fileType: 'Only PDF files are allowed.',
    fileSize: 'File upload failed.',
  },
  subjects: {
    loadFailed: 'Failed to load subject data.',
  },
  sections: {
    loaded: 'Sections loaded successfully.',
    loadFailed: 'Failed to load sections.',
  },
  curriculum: {
    loadFailed: 'Failed to load curriculum data.',
  },
  assignments: {
    added: 'Assignment added successfully.',
    addFailed: 'Failed to add assignment.',
    updated: 'Assignment updated successfully.',
    updateFailed: 'Failed to update assignment.',
    loadFailed: 'Failed to load assignment.',
    deleted: 'Assignment deleted successfully.',
    deleteFailed: 'Failed to delete assignment.',
    fileSize: 'File upload failed.',
    fileType: 'Only PDF files are allowed.',
    scoreUpdated: 'Score updated successfully.',
    scoreUpdateFailed: 'Failed to update score.',
    subjectRequired: 'Please select a Subject.',
    gradeRequired: 'Please select a Grade Level.',
    semesterRequired: 'Please select a Semester.',
    deadlineExpired: 'Submission deadline has passed. Unsubmitted students received 0.',
    scoreLocked: SCORE_LOCKED_MSG,
  },
  activities: {
    added: 'Activity added successfully.',
    addFailed: 'Failed to add activity.',
    updated: 'Activity updated successfully.',
    updateFailed: 'Failed to update activity.',
    loadFailed: 'Failed to load activity.',
    deleted: 'Activity deleted successfully.',
    deleteFailed: 'Failed to delete activity.',
    fileSize: 'File upload failed.',
    fileType: 'Only PDF files are allowed.',
    scoreUpdated: 'Score updated successfully.',
    scoreUpdateFailed: 'Failed to update score.',
    subjectRequired: 'Please select a Subject.',
    gradeRequired: 'Please select a Grade Level.',
    semesterRequired: 'Please select a Semester.',
    deadlineExpired: 'Submission deadline has passed. Unsubmitted students received 0.',
    scoreLocked: SCORE_LOCKED_MSG,
  },
  announcements: {
    added: 'Announcement added successfully.',
    addFailed: 'Failed to add announcement.',
    updated: 'Announcement updated successfully.',
    updateFailed: 'Failed to update announcement.',
    deleted: 'Announcement deleted successfully.',
    deleteFailed: 'Failed to delete announcement.',
    downloading: 'Downloading announcement...',
    imageType: 'Only PNG and JPG images are allowed.',
    imageSize: 'Photo too large. Maximum size is 2MB.',
    loadFailed: 'Failed to load announcements.',
  },
  quiz: {
    created: 'Quiz created successfully!',
    createFailed: 'Failed to create quiz.',
    updated: 'Quiz updated successfully!',
    updateFailed: 'Failed to update quiz.',
    deleted: 'Quiz deleted successfully!',
    deleteFailed: 'Failed to delete quiz.',
    loadFailed: 'Failed to load quizzes.',
    hidden: 'Quiz hidden from students',
    visible: 'Quiz is now visible to students',
    visibilityFailed: 'Failed to update quiz visibility.',
    passwordIncorrect: 'Incorrect password. Please try again.',
    passwordVerified: 'Password verified. Starting quiz...',
    scoreUpdated: 'Score updated successfully.',
    scoreUpdateFailed: 'Failed to update score.',
    scoreLocked: SCORE_LOCKED_MSG,
    deadlineRequired: 'Submission deadline is required.',
  },
  originality: {
    deleted: 'Report deleted successfully.',
    deleteFailed: 'Failed to delete report.',
    loadFailed: 'Failed to load reports.',
    createFailed: 'Failed to save analysis report.',
  },
}

export function useFacultyNotify() {
  const { notify } = useNotify()
  return useMemo(
    () => ({
      success: (msg, opts = {}) =>
        notify(msg, { durationMs: FACULTY_TOAST_MS, tone: 'success', ...opts }),
      error: (msg, opts = {}) =>
        notify(msg, { durationMs: FACULTY_TOAST_MS, tone: 'error', ...opts }),
      info: (msg, opts = {}) => notify(msg, { durationMs: FACULTY_TOAST_MS, tone: 'info', ...opts }),
      warning: (msg, opts = {}) =>
        notify(msg, { durationMs: FACULTY_TOAST_MS, tone: 'warning', ...opts }),
    }),
    [notify],
  )
}
